server:
  port: 8051

---
#MySql Database Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product-service
    username: root
    password: 8610425056aA@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
---
#Aws Manual Configuration
aws:
  s3:
    a
    s
    region: us-east-1
    bucket-name: demotry01
---
#Aws Image Size Setting
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB